import { describe, it, expect } from '@jest/globals';
import {
	count_antinode_locations,
} from "./lib.js";
	const testcases = [
		[`............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`, 14, 34],
	[`T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........`, 3, 9],
	];

describe("2024-12-08 p1", () => {
	for (let i = 0; i < testcases.length; i++) {
		it(`test-${i}`, () => {
			const tc = testcases[i];
			expect(count_antinode_locations(tc[0])).toBe(tc[1]);
		})
	}
});

describe("2024-12-08 p2", () => {
	for (let i = 0; i < testcases.length; i++) {
		it(`test-${i}`, () => {
			const tc = testcases[i];
			expect(count_antinode_locations(tc[0], 2)).toBe(tc[2]);
		})
	}
});

