import { describe, it, expect } from '@jest/globals';
import {
	exec,
} from "./lib.js";

describe("2016-12-08", () => {
	const testcases = [
		[`.......
.......
.......`, "rect 3x2", `###....
###....
.......`],
		[`###....
###....
.......`, "rotate column x=1 by 1", `#.#....
###....
.#.....`],
		[`#.#....
###....
.#.....`, "rotate row y=0 by 4", `....#.#
###....
.#.....`],
		[`....#.#
###....
.#.....`, "rotate column x=1 by 1", `.#..#.#
#.#....
.#.....`],
	];

	for (let i = 0; i < testcases.length; i++) {
		it(`test-${i}`, () => {
			const tc = testcases[i];
			const grid = tc[0].split("\n").map(line => line.split(""));
			exec(grid, tc[1]);
			expect(grid.map(row => row.join("")).join("\n")).toBe(tc[2]);
		})
	}
});

